### ISSUE TITLE
error while training data

### ISSUE THREAD

**Issue by lohithareddym** [EvilPort2/Sign-Language#17]
i am getting the following and yes there is no file and how is the code getting executed for u??

C:\Users\HP\Desktop\Sign-Language-master>python cnn_tf.py
Traceback (most recent call last):
  File "cnn_tf.py", line 114, in <module>
    tf.app.run()
  File "C:\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "cnn_tf.py", line 84, in main
    with open("train_images", "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'train_images'

**Comment by Sahil9771** [comment]
Hello, 
How did you resolve this issue, I'm having the same problem while running the code.

**Comment by EvilPort2** [comment]
use python load_images.py

**Comment by Sahil9771** [comment]
@EvilPort2 I ran the file and now i am getting a value error as follows:

Traceback (most recent call last):
  File "load_images.py", line 21, in <module>
    images_labels = pickle_images_labels()
  File "load_images.py", line 17, in pickle_images_labels
    images_labels.append((np.array(img, dtype=np.int32), int(label)))
ValueError: invalid literal for int() with base 10: 'gestures\\0\\1.jp'
Please revert asap. Thank you.

**Comment by EvilPort2** [comment]
That should not happen. Check if the files in your machine and GitHub is same or not. Btw the repo is updated. So download the latest files

**Comment by Sahil9771** [comment]
I cloned the project in morning and I'm using the tensorflow version which
is causing the problem.
Thank you.

**Comment by kirtigodani** [comment]
try executing python flip_images.py again

**Comment by EvilPort2** [comment]
Ok. There was a bug in the load_images.py I just saw. I did not think about cross compatibility while writing the code. This problem occurred to Windows users.  Now the problem should be solved for Windows users.

**Comment by akzhmdn** [comment]
can i use tensorflow 2.0?

**Comment by Athira97** [comment]
Hello, when I tried running the flip_images.py it ran successfully for quite a while and then gave a traceback error. In load_images.py also i got importError: DLL load failed. from sklearn.utils import shuffle. Please revert back asap. Thank you
