### ISSUE TITLE
ValueError: input arrays do not match

### ISSUE THREAD

**Issue by tsytiff** [EvilPort2/Sign-Language#22]
Hi I m running with the file **fun_util.py**

However, the  following **_Error_** occurs:

**Using TensorFlow backend.
Traceback (most recent call last):
  File "/xxx/Sign-Language-master-2/fun_util.py", line 317, in <module>
    recognize()
  File "/xxx/Sign-Language-master-2/fun_util.py", line 310, in recognize
    keypress = text_mode(cam)
  File "/xxx/Sign-Language-master-2/fun_util.py", line 284, in text_mode
    res = np.hstack((img, blackboard))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/shape_base.py", line 288, in hstack
    return _nx.concatenate(arrs, 1)
ValueError: all the input array dimensions except for the concatenation axis must match exactly**

Since I am a beginner learning this, I can't figure what's happening.
May you please help? Thank you.

**Comment by kirtigodani** [comment]
Try installing pyobjc using brew.Maybe this might work

**Comment by EvilPort2** [comment]
It is mainly due to difference in the camera that you are using. In my case my camera gave me a 640x480 image. So my blackboard variable was hard coded as such. Hence the error. The current version resizes the image to 640x480. So the error is no more.
