### ISSUE TITLE
Error about recognize_gestures.py

### ISSUE THREAD

**Issue by VuBrian22** [EvilPort2/Sign-Language#28]
$ python3 recognize_gesture.py
Traceback (most recent call last):
  File "recognize_gesture.py", line 4, in <module>
    from cnn_tf import cnn_model_fn
  File "C:\Users\REDACTED\Desktop\Sign-Language-master\cnn_tf.py", line 5, in <module>
    tf.logging.set_verbosity(tf.logging.INFO)
AttributeError: module 'tensorflow' has no attribute 'logging'

**Comment by EvilPort2** [comment]
You can remove the above line. What i mean is, in the cnn_tf.py you can remove that line.

**Comment by AfsanaReem** [comment]
If I remove that lines this happens:

"F:\Program Files\Python\Python37\python.exe" F:/PycharmProjects/Sign-Language-master/fun_util.py
2020-04-19 20:44:42.593982: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-04-19 20:44:42.594177: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using TensorFlow backend.
Traceback (most recent call last):
File "F:\Program Files\Python\Python37\lib\site-packages\pyttsx3_init_.py", line 20, in init
eng = _activeEngines[driverName]
File "F:\Program Files\Python\Python37\lib\weakref.py", line 137, in getitem
o = self.datakey
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "F:/PycharmProjects/Sign-Language-master/fun_util.py", line 11, in
engine = pyttsx3.init()
File "F:\Program Files\Python\Python37\lib\site-packages\pyttsx3_init_.py", line 22, in init
eng = Engine(driverName, debug)
File "F:\Program Files\Python\Python37\lib\site-packages\pyttsx3\engine.py", line 30, in init
self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
File "F:\Program Files\Python\Python37\lib\site-packages\pyttsx3\driver.py", line 50, in init
self.module = importlib.import_module(name)
File "F:\Program Files\Python\Python37\lib\importlib_init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1006, in _gcd_import
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "", line 728, in exec_module
File "", line 219, in _call_with_frames_removed
File "F:\Program Files\Python\Python37\lib\site-packages\pyttsx3\drivers\sapi5.py", line 10, in
import pythoncom
ModuleNotFoundError: No module named 'pythoncom'

Process finished with exit code 1

**Comment by Vivek16444** [comment]
Bro I need a help I will give fees

**Comment by Vivek16444** [comment]
Please bro

**Comment by VuBrian22** [comment]
> Bro I need a help I will give fees

The project is really old so the dependencies need to be updated in the code. I've fixed it for a project I used this code as a base a long time ago but you need to just update the code to the latest dependencies/modules, if that helps.
