### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by MacapagalDenver** [EvilPort2/Sign-Language#33]
i got a lot of errors. some i have fixed by i dont know what to do with the others. please help.

WARNING: Logging before flag parsing goes to stderr.
W0910 00:28:48.467671  4980 deprecation.py:506] From C:\Python\Python37\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\pydot.py", line 1915, in create
    working_dir=tmp_dir,
  File "C:\Python\Python37\lib\site-packages\pydot.py", line 136, in call_graphviz
    **kwargs
  File "C:\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\keras\utils\vis_utils.py", line 26, in _check_pydot
    pydot.Dot.create(pydot.Dot())
  File "C:\Python\Python37\lib\site-packages\pydot.py", line 1922, in create
    raise OSError(*args)
FileNotFoundError: [WinError 2] "dot" not found in path.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Sign-Language-master\cnn_keras.py", line 75, in <module>
    train()
  File "D:\Sign-Language-master\cnn_keras.py", line 68, in train
    model, callbacks_list = cnn_model()
  File "D:\Sign-Language-master\cnn_keras.py", line 47, in cnn_model
    plot_model(model, to_file='model.png', show_shapes=True)
  File "C:\Python\Python37\lib\site-packages\keras\utils\vis_utils.py", line 132, in plot_model
    dot = model_to_dot(model, show_shapes, show_layer_names, rankdir)
  File "C:\Python\Python37\lib\site-packages\keras\utils\vis_utils.py", line 55, in model_to_dot
    _check_pydot()
  File "C:\Python\Python37\lib\site-packages\keras\utils\vis_utils.py", line 29, in _check_pydot
    '`pydot` failed to call GraphViz.'
OSError: `pydot` failed to call GraphViz.Please install GraphViz (https://www.graphviz.org/) and ensure that its executables are in the $PATH.

**Comment by vermajahnvi** [comment]
@EvilPort2  i rqst u to plzz look into this prblm. i hv installed pydot and graphviz but still the error is same as mentioned above.

**Comment by MacapagalDenver** [comment]
I forgot what I've done but i already solved the problem I encountered

**Comment by EvilPort2** [comment]
It is a Graphviz installation problem. Install Graphviz and add the location of the executable to your PATH of your system. In Windows i think you need to set it from your Environment Variables.

**Comment by akzhmdn** [comment]
i did. 

still shows 

'pydot failed to call GraphViz.'
OSError: pydot failed to call GraphViz.Please install GraphViz (https://www.graphviz.org/) and ensure that its executables are in the $PATH.
