### ISSUE TITLE
Error while executing cnn_keras.py

### ISSUE THREAD

**Issue by rushikeshpolawar** [EvilPort2/Sign-Language#34]
Traceback (most recent call last):
  File "cnn_keras.py", line 75, in <module>
    train()
  File "cnn_keras.py", line 63, in train
    train_labels = np_utils.to_categorical(train_labels)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/np_utils.py", line 31, in to_categorical
    num_classes = np.max(y) + 1
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2505, in amax
    initial=initial)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by EvilPort2** [comment]
Use python 3
