### ISSUE TITLE
Error CNN-tf

### ISSUE THREAD

**Issue by Apoaqpeduli** [EvilPort2/Sign-Language#46]
Traceback (most recent call last):
  File "D:\Azhari\Tugas Akhir-2\Tunarungu\cnn_tf.py", line 114, in <module>
    tf.app.run()
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "D:\Azhari\Tugas Akhir-2\Tunarungu\cnn_tf.py", line 85, in main
    train_images = np.array(pickle.load(f))
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

im using numpy 1.15
opencv 3.4
tenserflow 1.4
keras 2.0.0

thanks

**Comment by RenNgu** [comment]
install the required module..i see you have numpy already installed but install "numpy.core._multiarray_umath" install it from the terminal or form your env or if those dont work install in manually
