### ISSUE TITLE
TypeError: Value passed to parameter 'input' has DataType uint8 not in list of allowed values: float16, bfloat16, float32, float64, int32

### ISSUE THREAD

**Issue by AnkitaMourya1999** [EvilPort2/Sign-Language#51]
Traceback (most recent call last):
  File "C:/Users/ankit/PycharmProjects/SLSWithVoice1/Sign-Language-master/cnn_tf.py", line 114, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "C:/Users/ankit/PycharmProjects/SLSWithVoice1/Sign-Language-master/cnn_tf.py", line 101, in main
    classifier.train(input_fn=train_input_fn, hooks=[logging_hook])
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1204, in _train_model_default
    self.config)
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "C:/Users/ankit/PycharmProjects/SLSWithVoice1/Sign-Language-master/cnn_tf.py", line 26, in cnn_model_fn
    name="conv1")
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow\python\keras\legacy_tf_layers\convolutional.py", line 437, in conv2d
    return layer.apply(inputs)
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 1722, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow\python\keras\legacy_tf_layers\base.py", line 551, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 786, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 667, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 396, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 478, in _call_unconverted
    return f(*args, **kwargs)
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 248, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1020, in convolution_v2
    name=name)
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1150, in convolution_internal
    name=name)
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2604, in _conv2d_expanded_batch
    name=name)
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 972, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 630, in _apply_op_helper
    param_name=input_name)
  File "C:\Users\ankit\PycharmProjects\SLSWithVoice1\venv\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 63, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'input' has DataType uint8 not in list of allowed values: float16, bfloat16, float32, float64, int32

**Comment by Anurag0987** [comment]
Hi @AnkitaMourya1999 did you solve the problem????

**Comment by AnkitaMourya1999** [comment]
> Hi @AnkitaMourya1999 did you solve the problem????

Not yet
